In [1]:
2+3

5

In [2]:
print("hello python")

hello python


In [3]:
name="NDV tech sys"
print("My Comany name is.." +  name)

My Comany name is..NDV tech sys


In [4]:
course="AI ML"
print("iam doing " + course)

iam doing AI ML


In [5]:
#Arthematic operators
# +. - , * , / , % , **


# addition
2+3


5

In [6]:
#subtraction
56-34

22

In [7]:
#multiplication
3*5

15

In [8]:
#divison
45/3

15.0

In [9]:
#floor divison
45//3

15

In [10]:
# modulous
45%6

3

In [11]:
#power
3**6

729

In [12]:
# variables
# variable is storage container which can able to store values as data types
# variable name is custom defined name
# variable name do not start with number
# variable name do not have spaces
# variable name do not have special chars
# ! @ # $ % ^ & * ( ) + = ' " " | \ ~  ? < >
# variable name should not be a python keyword or identifier
# if , elif def in as ,....

# variable name can allow one special char which is underscore _

name = "srinivas" # str
age=34 # int
Qual="MCA" # str
Techs=["java",'python','ML'] # list



In [13]:
1empname="srini"

SyntaxError: invalid decimal literal (<ipython-input-13-2486656919>, line 1)

In [ ]:
emp name ="srini"
emp name

In [ ]:
emp$name ='srini'
emp$name

In [ ]:
emp_name="srini"
emp_name

In [ ]:
if ="srini"
if

In [ ]:
# datatypes

# int
x=100
print (type(x))
# float
y=10.234
print(type(y))
# bool
isGraduated= True
print(type(isGraduated))
# str
name = "NDVTechsys" # operations
print(type(name))
# list
names =['srini','srini','ramesh','rajesh','suresh','somesh'] # operations
print(names)
print(type(names)) # list will allow duplicates
# tuple
fruits=('apple','mango','bannana')
print(type(fruits))
# set
names1 = { 'srini','srini','srini','srini','ramesh','rajesh','suresh','somesh'}
print(type(names1)) # set will not allow duplicates
print(names1)

# dict
emp_info={"emp_name":"srini","age":34,"Qual":"MCA"}
print(type(emp_info))
print(emp_info)

In [ ]:
# list is mutable means we can add objects ,delete objects ,insert objects for list
# list is index based [0,1,2,3,4..]
# list is ordered collection

# tuple is immutable means we cannot add ,delete,insert objects
# tuple is index based [0,1,2,3,4,5..]
# tuple allowed duplicates
# tuple is ordered collection

# set is not allowed duplicates
# set is not index based : un ordred collection

# string also orderd collction
# 'srini' ['s','r','i','n','i'] : [0,1,2,3,4]
# string is immutable we cannot perform add,delete,insert kind of operations.

#dict is collction of key:value pair system
# dict we can add , remove ,replace
# dict is not ordered collction , no index based
# key and value seperated with :



In [ ]:
# python predefined functions

# print()
# input()
# type()
# id()


# type casting functions
# int()
# float()
# str()
# list()
# tuple ()
# set()


In [ ]:
# print()
print("hello python")
print('hello python')
print('''hello python''')
print("""hello python""")


In [ ]:
#print formating
# srinivas teaching python course for 6000 rs
name ="srinivas"
course_name="python"
course_price=6000
print(name+ " teching " + course_name + " course for " + str(course_price) + " rs")
print("{0} teching {1} course for {2} rs".format(name,course_name,course_price))
print(f"{name} teching {course_name} course for {course_price} rs")

In [ ]:
# input()
# taking input value from user
# input() function will take data deafut string type
prd_price=float(input("enter your product price"))
prd_discount=float(input("enter discount for the product"))
final_price= prd_price-prd_discount # '45000'-'4550' # str-str
print("final price of the product is..",final_price)


In [ ]:
name ='srinivas'
print(type(name))
print(id(name))

In [14]:
# operators
# loops
# conditions
# functions
# oops
# json
# mini project

In [15]:
#operators
# arthematic
# relational
# inc dec
# assignment
# membership
# logical

In [16]:
# arthematic
# + - * / //  %  **

In [17]:
#relational operators : <  <=  >  >= !=
3<4

True

In [18]:
5>78

False

In [19]:
67<=67

True

In [20]:
89>=89

True

In [21]:
2!=3

True

In [22]:
# comarison
# ==
2==2

True

In [23]:
'2'==2

False

In [24]:
"srinivas" == "Srinivas"

False

In [25]:
"srinivas" != "Srinivas"

True

In [26]:
# inc / dec

In [27]:
a=100
a

100

In [28]:
a+=10 # a =a+10
# a = 100+10
a

110

In [29]:
a*=3
a

330

In [30]:
a/=4
a

82.5

In [31]:
# membership
# in , is
name = "Srinivas"
'n' in name

True

In [32]:
'z' in name

False

In [33]:
names =['srini','laxmi','likitha','chandra']
'sowji' in names

False

In [34]:
# is  same like ==
's' is "S"

<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
<ipython-input-34-1068352359>:2: SyntaxWarning: "is" with a literal. Did you mean "=="?
  's' is "S"


False

In [35]:
# logical operators

# logical and (&&)  Python ( and )
# t and t -> t
# f and t -> f
# t and f -> f
# f and f -> f
# if both statements are true then final result will be true .

# logical or (||).  Python ( or )
# t or f -> t
# f or t -> t
# f or f -> f
# t or t -> t
# if any one of the statement is true final result will be true .

4>5 and 5<7
# f and t  -> f


False

In [36]:
4>5 or 5<7
# f or t


True

In [37]:
# indentation
# indentation is python code editor rule .
# all the statements in python editor should fallow same column space
# general code no spaces.

# if we find any block statements then minimum one space indentation needed
# conditions , loops ,functions ,classes ..


print("hello")
print("hello")
print("hello")
print("hello")


hello
hello
hello
hello


In [38]:
# conditions
# if  : check only true blocks
# if else : check true and flase blocks
# elif : cheks more true blocks if any true block not sartisfy finally it will go for false

In [39]:
# if  : check only true blocks
name ="srinivas"

#---
if name == "srinivas": # false
  print('true block starts here.. ')
  print("mathed")
#----

print("this statement is out of block")


true block starts here.. 
mathed
this statement is out of block


In [40]:
# if else : check true and flase blocks

name="Srinivas"
#-- block starts
if name=="srinivas":
  print('matched')
  print("iam still in true block")
else:
  print("not matched")
  print("iam in false block")
#-- block ends



not matched
iam in false block


In [41]:
# elif : cheks more true blocks if any true block not sartisfy finally it will go for false

In [42]:
speed=70

if speed<30:
  print("going very slow")
elif speed>30 and speed<60:
  print("avg speed")
elif speed>60 and speed<90:
  print("good speed")
else:
  print("too fast")


good speed


In [43]:
#loops
# loops are itterrations
# while loop
# for in
# break
# continue


In [44]:
# while loop
a=0
while a<5 :
  print(a)
  a+=1

0
1
2
3
4


In [45]:
# for in
for a in range(7):
  print(a)


0
1
2
3
4
5
6


In [46]:
for num in range(5,100,12): # 0-100 , 11 step
  print(num)

5
17
29
41
53
65
77
89


In [47]:
for char in "Srinivas":
  print(char)

S
r
i
n
i
v
a
s


In [48]:
names
for name in names:
  print(name)

srini
laxmi
likitha
chandra


In [49]:
# i want print a name with only 5 chars
for name in names:
  if len(name)==5:
    print(name)

srini
laxmi


In [50]:
# filter even
for num in range(0,10): # 0-100 , 11 step
  if num%2==0:
    print(num)

0
2
4
6
8


In [51]:
# filter even
for num in range(0,10): # 0-100 , 11 step
  if num%2!=0:
    print(num)

1
3
5
7
9


In [52]:
# functions
# functions are set of statements for execute specific functionality
# in python function defined with def keyword
# functions are fallowing indentation.

# function name should need fallow some rules
# def name should not start with number
# def name should not have spaces
# def name cannot contain special chars
# def name should not be a python keyword / identifier
# def name should ended with ()
# def name will allow one special char called underscore _
# when we define a def we need to call ..

In [53]:
# def init
def hello():
  print("hello python")
  print("iam in function block")

# calling def
hello()

hello python
iam in function block


In [54]:
def 1emp():
  print("emp")

# def name should not start with number


SyntaxError: invalid decimal literal (<ipython-input-54-2067381864>, line 1)

In [ ]:
def if():
  print("hello")
# def name should not be a python keyword / identifier


In [ ]:
def emp name():
  print("srini")
# def name should not have spaces


In [ ]:
def emp%name():
  print("hello python")
# def name cannot contain special chars


In [55]:
def emp_name():
  print("srini")
emp_name()

srini


In [ ]:
# functions types
# 1.function with out having return types and parameters (basic function)
# 2.functions with parameters
# 3.functions with return type
# 4.function with parameter and return type
# 5.lambda functions (no name specified functions) (short hand functions)


In [56]:
# 2.functions with parameters
def add(a,b):
  sum = a+b
  print("summation",sum)

# calling function
add(12,45)

summation 57


In [57]:
add(100,456)

summation 556


In [58]:
def fullname(f_name,l_name):
  fullname=f_name+ ' ' +l_name
  print("your full name is ..",fullname)
fullname('srini','gorantla')


your full name is .. srini gorantla


In [61]:
def employee_details(emp_id,emp_name,salary):
  print("{0} named person getting {1} salary for employee id {2}".format(emp_name,salary,emp_id))

employee_details(1001,"srini",89000)
employee_details(1002,"nandini",50000)



srini named person getting 89000 salary for employee id 1001
nandini named person getting 50000 salary for employee id 1002


In [ ]:
# 3.functions with return type with parameters
def getName(name):
  return name
my_name=getName("srini")
print("myname is ..",my_name)

In [62]:
#4. functions  with return no params
def say_Hello():
  return "Hello Python ML AI developers"
print(say_Hello())

Hello Python ML AI developers


In [63]:
# lambda functions (tiny functions)
add = lambda a,b :a+b
add(23,34)

# def add(a,b):
#   sum = a+b
#   print("summation",sum)
# # calling function
# add(12,45)

57

In [64]:
# map() with lambda
numbs = [1,2,3,4,5,6]
sqaured_nums=list(map(lambda x:x**2,numbs))
print(sqaured_nums)


[1, 4, 9, 16, 25, 36]


In [66]:
#filter with lambda even
even_nums=list(filter(lambda x:x%2==0,numbs))
print(even_nums)

[2, 4, 6]


In [67]:
#filter with lambda odd
odd_nums=list(filter(lambda x:x%2!=0,numbs))
print(odd_nums)

[1, 3, 5]


In [68]:
names = ['ramya','sirisha','sruthi','sravya','ansh','srinivas']
#filter 6 digit names
filtered_names=list(filter(lambda x:len(x)==6,names))
filtered_names

['sruthi', 'sravya']

In [ ]:
#EDA : Exploratory Data Analysis

# EDA is key initial step for machine leaerning pipe line .
# it involves analyzing and visualizing data to understand structure, detect patterens

# numpy
# pandas
# matplotlib
# seaborn
# scipy

# EDA helps
# EDA is used for undestand the distribution and nature of the data
# identify missing values ,ouliers and inconsistance
# discover relationship between variables
# choose right features ,transformations or ML alogorithms .

# EDA STEPS

# 1.Data collection
# 2.Data overview
# 3.Missing value alalysis
# 4.Univariante Analysys
# 5.Bivariante analysys
# 6.outlier detection
# 7.feature enginnering

In [ ]:
# numpy

# python programming : list
# numpy  :  single dim arrays or multi dim arrays , matrix  1D 2D 3D ...ND
# MATRIX operations


# New section
NumPy, short for Numerical Python, is a fundamental open-source library in Python for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a comprehensive collection of high-level mathematical functions to operate efficiently on these arrays.


In [1]:
# import numpy
# https://numpy.org/    is  official site where we can find out documentation.

import numpy as np


In [8]:
list1=[1,2,3,4,5]
list1


[1, 2, 3, 4, 5]

In [9]:
type(list1)

list

In [6]:
a=np.array([1,2,3,4]) # 1 min
a

array([1, 2, 3, 4])

In [7]:
type(a)

numpy.ndarray

In [18]:
a.shape

(4,)

In [12]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
b.shape

(2, 3)

In [13]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
c.shape

(3, 3)

In [19]:
c[0]

array([1, 2, 3])

In [20]:
c[1]

array([4, 5, 6])

In [21]:
c[2]

array([7, 8, 9])

In [22]:
c[0][0]

np.int64(1)

In [23]:
c[1][1]

np.int64(5)

In [25]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.arange(0,100,12) # (start_num,end_num,step_num)

array([ 0, 12, 24, 36, 48, 60, 72, 84, 96])

In [31]:
# indexing slicing
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
c[0] # first row

array([1, 2, 3])

In [32]:
c[:,0] # first column

array([1, 4, 7])

In [34]:
c[:,1] # second column

array([2, 5, 8])

In [ ]:
#pandas
#pandas is panel data sets

In [35]:
import pandas as pd

In [36]:
df = pd.DataFrame(
    {
        "Name": [
            "Braund, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnell, Miss. Elizabeth",
        ],
        "Age": [22, 35, 58],
        "Sex": ["male", "male", "female"],
    }
)


In [37]:
df

Name  Age     Sex
0   Braund, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnell, Miss. Elizabeth   58  female

In [38]:
df["Age"]

0    22
1    35
2    58
Name: Age, dtype: int64

In [40]:
df["Name"]

0     Braund, Mr. Owen Harris
1    Allen, Mr. William Henry
2    Bonnell, Miss. Elizabeth
Name: Name, dtype: object